### ISSUE TITLE
error due to missing peerDep of isomorphoc-ws when using yarn 4 in pnp mode

### ISSUE THREAD

**Issue by adrian-gierakowski** [sukovanej/effect-http#478]
Hi, first thanks for this great project! I'm hoping to replace https://github.com/BitGo/api-ts with it

however, running a simple http server example from Readme.md I get:

```
Error: isomorphic-ws tried to access ws (a peer dependency) but it isn't provided by its ancestors; this makes the require call ambiguous and unsound.

Required package: ws
Required by: isomorphic-ws
```

Installing ws in my project doesn't help. I believe ws should be added to peerDeps of effect-http in order to fix this

btw. it would be great if this was not required for simple http server as I guess it doesn't actually use the websocket lib

**Comment by adrian-gierakowski** [comment]
hey, sorry, just realised that isomorphic-ws is imported by @effect/platform, so I should raise the issues in their repo

**Comment by adrian-gierakowski** [comment]
although once they add ws a peerDep, effect-http should add it as well, so I'll come back to reopen the issue once it's solved in @effect/platform 

for the time being, it can be patched by adding the following in `.yarnrc.yml`:

```yml
packageExtensions:
  "effect-http@*":
    peerDependencies:
      ws: "*"

  "@effect/platform@*":
    peerDependencies:
      ws: "*"
```
